### PR TITLE
ProductsController

### LINKED ISSUE #16: Add controller/action for browsing products
Suggested api route is `GET api/products`.

Child of #3.

### PR DESCRIPTION
**Pull request by Barraza44**
closes #16

### CODE REVIEW

**Comment by Palisar** [comment]
just looking through your code can you change the name of the InsetProductHelper to InsertProductHandler?

**Comment by Barraza44** [comment]
> just looking through your code can you change the name of the InsetProductHelper to InsertProductHandler?

I think that's on #35 tho

**Comment by Palisar** [comment]
> > just looking through your code can you change the name of the InsetProductHelper to InsertProductHandler?
> 
> I think that's on #35 tho

You are correct haha my mistake

**Review by pobiega — APPROVED** [review]

**Comment by pobiega** [comment]
I think this PR can be closed, as these exact changes have already been done with Ilyas PR.

**Pull request closed without merging**
