### PR TITLE
Blazor Product Moded

### LINKED ISSUE #54: (Draft) Add our product model to the blazor project to access the api with
We need a product model since the model in use with the API has inits that we cannot use.

### PR DESCRIPTION
**Pull request by Palisar**
Added this so we can talk to the API via refit

### CODE REVIEW

**Comment by valincius** [comment]
You should use `Congo.Contracts.Responses.Products.ProductResponse` instead. The contracts product is so we can have identical models to use between frontend and backend.

Edit: never mind I see now, will get back to you

**Comment by Palisar** [comment]
> You should use `Congo.Contracts.Responses.Products.ProductResponse` instead. The contracts product is so we can have identical models to use between frontend and backend.

we  had just talked about this in the meeting and are going to impliment refit, and the blazor project needs its own product model to uses this, or so im told

**Comment by valincius** [comment]
Ok I see. We are losing one of the main benefits of Blazor (sharing models between API & client app) by doing this, but I guess we can treat them as independent applications and go with this route.

**Comment by Palisar** [comment]
> Ok I see. We are losing one of the main benefits of Blazor (sharing models between API & client app) by doing this, but I guess we can treat them as independent applications and go with this route.

Honestly I'm not sure of the benifits or pitfalls of doing it either way, i just opened up the issue becuause we had mentioned it in the meeting but if you think that we will be loosing out on something by doing it this way then i would like to hear you out, we can continue the discussion in Congo chat

**Comment by ThorstenSauter** [comment]
I think it may have been a bit confusing in the meeting. Using responses from the Contracts project should be just fine in the Blazor, as well as the RazorPages projects, as long as you don't intend for them to be changed by the user (since they are immutable). On the other hand, using the requests from the Contract project for direct user input seems problematic, since there is probably not always a one-to-one mapping between the form input and what the API expects. Using a separate model for the form also retains the ability to do client-side validation before sending the form.

**Comment by valincius** [comment]
Yeah maybe use the Contracts model for Refit then map/convert the responses to our Blazor view model?
We wouldn't be able to just call `IProductsRefitService.GetProducts();` and use that directly then since we'd need to do some mapping in between (Contract -> ViewModel), so that might need some work.

And if we wanted validation on one of the models, we'd be duplicating a lot. Since we'd have essentially the same validation being copied and pasted on the frontend and backend.

**Pull request closed without merging**
